name: publish
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: window-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      # 배포를 위한 명령어들
      - run: yarn build
      - run: npm patch version
      - run: npm publish --access public

        # NPM Access 토큰
        env:
          NODE_AUTH_TOKEN: $
